server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  retryable: true
  prefix: /api
  strip-prefix: true
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
  routes:
    products:
      path: /catalog/**
      serviceId: catalog
    enterprise:
      path: /enterprise/**
      serviceId: companies
    authenticator:
      path: /authenticator/**
      serviceId: authenticator

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
      